title: Paweł Patorski
logo: 
description: Zajmuję się kompleksową analizą i modelowaniem procesów, których celem jest identyfikacja potencjałów do doskonalenia w zakresie rozwiązań IT. Nabyłem doświadczenie w obszarze definiowania klienta wewnętrznego, współpracy z developerami, wdrażania aplikacji webowych oraz desktopowych wraz z zapewnieniem procesu szkoleniowego. Mam doświadczenie w zakresie utrzymania i administracji wdrożonych aplikacji i systemów. Biorę udział również w testowaniu, raportowaniu błędów oraz optymalizacji wdrożonych rozwiązań.
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
