remote_theme: pages-themes/cayman@v0.2.0
plugins: 
- jekyll-remote-theme 
logo: /assets/img/foto.png
title: Paweł Patorski 
description: Zajmuję się kompleksową analizą i modelowaniem procesów, których
celem jest identyfikacja potencjałów do doskonalenia w zakresie
rozwiązań IT.
